// PowerUpManager contract ABI
export const POWERUPMANAGER_ABI = [
  {
    inputs: [
      { name: "player", type: "address" },
      { name: "powerUpId", type: "uint256" },
      { name: "upgradeHash", type: "bytes32" },
      { name: "signature", type: "bytes" },
    ],
    name: "upgradePowerUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "powerUpId", type: "uint256" },
      { name: "baseCost", type: "uint256" },
      { name: "maxLevel", type: "uint256" },
    ],
    name: "setPowerUpEmergency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "player", type: "address" },
      { name: "powerUpId", type: "uint256" },
    ],
    name: "upgradePowerUpEmergency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "powerUpId", type: "uint256" },
      { name: "baseCost", type: "uint256" },
      { name: "maxLevel", type: "uint256" },
    ],
    name: "setPowerUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "player", type: "address" }],
    name: "getPowerUpLevels",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "powerUpId", type: "uint256" }],
    name: "getPowerUpConfig",
    outputs: [
      { name: "cost", type: "uint256" },
      { name: "maxLevel", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "player", type: "address" },
      { name: "powerUpId", type: "uint256" },
    ],
    name: "getPowerUpUpgradeCost",
    outputs: [{ name: "cost", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "powerUpBaseCosts",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "powerUpMaxLevels",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "powerUpId", type: "uint256" },
      { name: "level", type: "uint256" },
    ],
    name: "getPowerUpLevelCost",
    outputs: [{ name: "cost", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    name: "levels",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractInfo",
    outputs: [
      { name: "gameOwner", type: "address" },
      { name: "paused", type: "bool" },
      { name: "minTimeBetweenUpgrades", type: "uint256" },
      { name: "securityKeySet", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "securityKey", type: "bytes32" }],
    name: "setSecurityKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "newGameOwner", type: "address" }],
    name: "setGameOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "newPaused", type: "bool" }],
    name: "setPaused",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "newGameServer", type: "address" }],
    name: "setGameServer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "newRiceManager", type: "address" }],
    name: "setRiceManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
