# Configuration for automatic labeling of pull requests
# Format for actions/labeler@v5

component:
  - changed-files:
      - any-glob-to-any-file: "src/components/**/*"

hooks:
  - changed-files:
      - any-glob-to-any-file: "src/hooks/**/*"

state-management:
  - changed-files:
      - any-glob-to-any-file: "src/store/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*.test.*"
          - "src/**/*.spec.*"
          - "src/**/__tests__/**/*"
          - "__tests__/**/*"
          - "test/**/*"
          - "tests/**/*"

styling:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.css"
          - "**/*.scss"
          - "**/*.sass"
          - "**/*.less"
          - "src/app/globals.css"

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - ".github/**/*"
          - "package.json"
          - "package-lock.json"
          - "yarn.lock"
          - "tsconfig.json"
          - "eslint.config.*"
          - "jest.config.*"
          - "next.config.*"
          - "postcss.config.*"
          - "vercel.json"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "yarn.lock"

i18n:
  - changed-files:
      - any-glob-to-any-file:
          - "src/languages/**/*"
          - "**/i18n/**/*"
          - "**/locales/**/*"

game-logic:
  - changed-files:
      - any-glob-to-any-file:
          - "src/utils/gameLogic.ts"
          - "src/utils/gameRenderer.ts"
          - "src/constants/game.ts"
          - "src/types/game.ts"

ui:
  - changed-files:
      - any-glob-to-any-file:
          - "src/components/Game*.tsx"
          - "src/components/GameUI.tsx"
          - "src/components/GameCanvas.tsx"
