name: Auto Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const isFromFork = context.payload.pull_request.head.repo.full_name !== context.repo.owner + '/' + context.repo.repo;

            // Don't delete branches from forks or protected branches
            const protectedBranches = ['main', 'master', 'develop', 'development', 'staging', 'production'];

            if (isFromFork) {
              console.log('Branch is from a fork, skipping deletion');
              return;
            }

            if (protectedBranches.includes(branchName)) {
              console.log(`Branch ${branchName} is protected, skipping deletion`);
              return;
            }

            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });
              console.log(`Successfully deleted branch: ${branchName}`);
            } catch (error) {
              console.log(`Failed to delete branch ${branchName}: ${error.message}`);
              // Don't fail the workflow if branch deletion fails
            }
