name: Auto Label PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto assign author
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;

            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [author]
              });
              console.log(`Successfully assigned PR to author: ${author}`);
            } catch (error) {
              console.log(`Failed to assign PR to author ${author}:`, error.message);
            }
